project:
  type: website
  output-dir: docs

website:
  title: "Sam Kirkham - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"
  
  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.md
      - text: "Blog"
        href: blog.qmd
      - text: "Projects"
        menu:
          - text: "All Projects"
            href: index.md
          - text: "---" 
          - text: "Data Wrangling ang Visualization"
            href: blog.qmd
    right:
      - icon: github
        href: https://github.com/Sam-Kirkham
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-kirkham-1b3730385/ 

  sidebar:
    - title: "Projects"
      contents:
        - index.md
        - blog.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
